### ISSUE TITLE
Vamos a ponernos las pilas pendejo 

### ISSUE THREAD

**Issue by SDGM21** [Nick1919/Proyecto-Pana#2]
Xd

**Comment by Nick1919** [comment]
Aaaaaaaaa no quiero

**Comment by SDGM21** [comment]
xdddddddd matate matate

**Comment by Nick1919** [comment]
Siva ya vi la repo. Mañana temprano le echo un ojo a ese code. Ahorita es
bullde tarde y tengo vullde sueño. Ando cansando me bullda últimamente

**Comment by SDGM21** [comment]
- [ ] njd
